# Generated by Django 6.0.7 on 2026-07-29 11:48

import apps.common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Ism-familiya')),
                ('phone', models.CharField(max_length=20, validators=[apps.common.validators.validate_phone], verbose_name='Telefon')),
                ('route_from', models.CharField(blank=True, max_length=150, verbose_name='Qayerdan')),
                ('route_to', models.CharField(blank=True, max_length=150, verbose_name='Qayerga')),
                ('date_needed', models.DateField(blank=True, null=True, verbose_name='Kerakli sana')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processing', 'Jarayonda'), ('done', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='new', max_length=20, verbose_name='Holat')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services.servicedirection', verbose_name="Xizmat yo'nalishi")),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fleet.vehicle', verbose_name='Transport vositasi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
