# Generated by Django 6.0.7 on 2026-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_needed',
        ),
        migrations.AddField(
            model_name='order',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi'),
        ),
    ]
