# Generated by Django 6.0.7 on 2026-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(max_length=255, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(verbose_name="To'liq tavsif")),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon klassi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': "Xizmat yo'nalishi",
                'verbose_name_plural': "Xizmat yo'nalishlari",
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon klassi')),
            ],
            options={
                'verbose_name': 'Xizmat afzalligi',
                'verbose_name_plural': 'Xizmat afzalliklari',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
