# Generated by Django 6.0.7 on 2026-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_vehicle_options_vehicle_delivery_time_minutes_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedirection',
            name='suitable_vehicles',
            field=models.ManyToManyField(blank=True, related_name='suitable_services', to='fleet.vehicle', verbose_name='Mos transport vositalari'),
        ),
        migrations.AddField(
            model_name='servicedirection',
            name='what_is_included',
            field=models.TextField(blank=True, help_text='Har bir qatorga bir element yozing. Masalan:\nHaydovchi bilan avtomobil\nAeroportga kutib olish\n24/7 dispetcher', verbose_name='Xizmatga nimalar kiradi (Что входит)'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='description',
            field=models.CharField(blank=True, help_text='Masalan: Podача точно в срок', max_length=200, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='servicedirection',
            name='description',
            field=models.TextField(help_text="Detail sahifada ko'rsatiladi", verbose_name="To'liq tavsif"),
        ),
        migrations.AlterField(
            model_name='servicedirection',
            name='short_description',
            field=models.CharField(help_text="Kartochkada ko'rsatiladi", max_length=255, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Masalan: fas fa-clock', max_length=50, verbose_name='Icon klassi'),
        ),
    ]
