# Generated by Django 6.0.7 on 2026-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_main', models.CharField(blank=True, max_length=20, verbose_name='Asosiy telefon')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('work_hours', models.CharField(blank=True, default='09:00 - 18:00', max_length=100, verbose_name='Ish vaqti')),
                ('work_days', models.CharField(blank=True, default='Dushanba - Shanba', max_length=100, verbose_name='Ish kunlari')),
                ('stat_vehicles_count', models.PositiveIntegerField(default=30, verbose_name='Texnika soni (30+)')),
                ('stat_experience_years', models.PositiveIntegerField(default=8, verbose_name='Ish tajribasi (8 yil)')),
                ('stat_clients_count', models.PositiveIntegerField(default=500, verbose_name='Mijozlar soni (500+)')),
                ('stat_support', models.CharField(default='24/7', max_length=20, verbose_name="Qo'llab-quvvatlash")),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_link', models.URLField(blank=True, verbose_name='YouTube')),
                ('site_title', models.CharField(blank=True, default='ARTRANS', max_length=100, verbose_name='Sayt nomi')),
                ('site_description', models.CharField(blank=True, max_length=255, verbose_name='Sayt tavsifi')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
            },
        ),
    ]
