# Generated by Django 6.0.7 on 2026-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='delivery_time_minutes',
            field=models.PositiveIntegerField(default=15, verbose_name='Avtomobil yetkazib berish vaqti (daqiqada)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='dispatch_hours',
            field=models.CharField(blank=True, default='круглосуточно', max_length=100, verbose_name='Dispetcher ish vaqti'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='response_time_minutes',
            field=models.PositiveIntegerField(default=15, verbose_name='Menejer javob vaqti (daqiqada)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_categories_count',
            field=models.PositiveIntegerField(default=6, verbose_name='Kategoriyalar soni'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_vehicles_label',
            field=models.CharField(blank=True, default='единиц', max_length=50, verbose_name='Texnika soni — label'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sunday_schedule',
            field=models.CharField(blank=True, default='по запросу', max_length=100, verbose_name='Yakshanba ish tartibi'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Masalan: https://wa.me/998901234567', verbose_name='WhatsApp havolasi'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.CharField(blank=True, help_text='Masalan: г. Ташкент, Узбекистан', max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone_main',
            field=models.CharField(blank=True, help_text="Masalan: +998901234567 — header va footer da ko'rsatiladi", max_length=20, verbose_name='Asosiy telefon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_description',
            field=models.CharField(blank=True, help_text='Masalan: Транспортные услуги для бизнеса, туризма и частных клиентов', max_length=255, verbose_name='Sayt tavsifi'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_clients_count',
            field=models.PositiveIntegerField(default=500, verbose_name='Mijozlar soni'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_experience_years',
            field=models.PositiveIntegerField(default=8, verbose_name='Tajriba yillari'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_support',
            field=models.CharField(blank=True, default='24/7', max_length=20, verbose_name="Qo'llab-quvvatlash"),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_vehicles_count',
            field=models.PositiveIntegerField(default=30, verbose_name='Texnika soni'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='telegram_link',
            field=models.URLField(blank=True, verbose_name='Telegram havolasi'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='work_days',
            field=models.CharField(blank=True, default='Пн — Сб', max_length=100, verbose_name='Ish kunlari'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='work_hours',
            field=models.CharField(blank=True, default='08:00 – 20:00', max_length=100, verbose_name='Ish vaqti'),
        ),
    ]
