# Generated by Django 6.0.7 on 2026-07-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available_today',
            field=models.BooleanField(default=False, verbose_name='Доступно сегодня (Bugun mavjud)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rang'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('gas', 'Gaz'), ('hybrid', 'Gibrid'), ('electric', 'Elektr')], max_length=20, verbose_name="Yoqilg'i turi"),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_ac',
            field=models.BooleanField(default=False, verbose_name='Konditsioner'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_climate_control',
            field=models.BooleanField(default=False, verbose_name='Klimat-kontrol'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_driver',
            field=models.BooleanField(default=False, verbose_name='С водителем (Haydovchi bilan)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_negotiable',
            field=models.BooleanField(default=False, verbose_name='Narx kelishiladi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('auto', 'Avtomat'), ('manual', 'Mexanik')], max_length=20, verbose_name='Uzatmalar qutisi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Model nomi'),
        ),
    ]
