# Generated by Django 6.0.7 on 2026-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_available_today_vehicle_brand_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['category__order', 'name'], 'verbose_name': 'Transport vositasi', 'verbose_name_plural': 'Transport vositalari'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='delivery_time_minutes',
            field=models.PositiveIntegerField(default=15, verbose_name='Yetkazib berish vaqti (daqiqada)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='discount_from_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Chegirmali ijara (kundan)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, default='Tashkent', max_length=100, verbose_name='Joylashuv'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_rental_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimal ijara muddati (kun)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rental_conditions',
            field=models.TextField(blank=True, help_text='Har bir qatorga bir shart yozing. Masalan:\nDepolit talab qilinmaydi\nBepul bekor qilish 24 soat oldin', verbose_name='Ijara shartlari (Условия аренды)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='suitable_for',
            field=models.TextField(blank=True, help_text='Har bir qatorga bir variant yozing. Masalan:\nDelegatsiyalar\nVIP sayohatlar\nHavo maydoni transfer', verbose_name='Nimaga mos (Подходит для)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('gas', 'Gaz'), ('hybrid', 'Gibrid'), ('electric', 'Elektromobil')], max_length=20, verbose_name="Yoqilg'i turi"),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_negotiable',
            field=models.BooleanField(default=True, verbose_name='Narx kelishiladi (Цена договорная)'),
        ),
    ]
